data:
  raw_dir: data/raw
  processed_dir: data/processed
  leftover_file: df_final.csv

split:
  test_size: 0.2
  random_state: 42

model:
  xgboost:
    n_estimators: 700
    max_depth: 8
    learning_rate: 0.05
  lightgbm:
    n_estimators: 700
    max_depth: 8
    learning_rate: 0.05
  catboost:
    iterations: 700
    depth: 8
    learning_rate: 0.05
  random_forest:
    n_estimators: 100
    max_depth: null

features:
  cat_cols:
    - airline
    - origin_airport
    - dest_airport
